/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from 'react';
import {
  Table,
  Button,
  Space,
  Tag,
  Card,
  Typography,
  Select,
  Row,
  Col,
  Statistic,
} from 'antd';
import {
  EnvironmentOutlined,
  AppstoreOutlined,
  ClearOutlined,
} from '@ant-design/icons';
import { useQuery} from '@tanstack/react-query';
import { blueprintService } from '../api/blueprintService';
import { racksApi } from '../api/racks';
import { locationsApi} from '../api';
import type { Location } from '../types/entities';
import { formatDate } from '../utils/dateFormatter';
import { useAuthStore } from '../store/authStore';
import type { ColumnsType } from 'antd/es/table';
import { AppColors } from '../constants/colors';

const { Title, Text } = Typography;
export default function Locations() {
  const [selectedBlueprint, setSelectedBlueprint] = useState<string | null>(null);
  const [selectedRack, setSelectedRack] = useState<string | null>(null);
  const user = useAuthStore((state) => state.user);
  const isAdmin = user?.role === 'Admin';

  const { data: blueprints } = useQuery({
    queryKey: ['blueprints'],
    queryFn: blueprintService.getAll,
  });

  const { data: racks } = useQuery({
    queryKey: ['racks', selectedBlueprint],
    queryFn: () => racksApi.getByBlueprintId(selectedBlueprint!),
    enabled: !!selectedBlueprint,
  });

  const { data: locations, isLoading } = useQuery({
    queryKey: ['locations', selectedBlueprint, selectedRack],
    queryFn: locationsApi.getAll,
  });

  const filteredLocations = locations?.filter((location) => {
    if (selectedRack) {
      return location.rackId === selectedRack;
    }
    if (selectedBlueprint && location.rack) {
      return location.rack.blueprintId === selectedBlueprint;
    }
    return true;
  });

  const stats = {
    total: filteredLocations?.length || 0,
    withRack: filteredLocations?.filter((l) => l.rackId).length || 0,
    withoutRack: filteredLocations?.filter((l) => !l.rackId).length || 0,
    autoGenerated: filteredLocations?.filter((l) => l.rackId && l.rowNumber && l.gridNumber).length || 0,
  };




  const handleClearFilters = () => {
    setSelectedBlueprint(null);
    setSelectedRack(null);
  };

  const columns: ColumnsType<Location> = [
    {
      title: 'Rack',
      key: 'rack',
      width: '12%',
      render: (_: any, record: Location) => {
        if (record.rack) {
          return (
            <Space direction="vertical" size={0}>
              <Tag color="purple" icon={<AppstoreOutlined />}>
                {record.rack.name}
              </Tag>
              {record.rowNumber && record.gridNumber && (
                <Text type="secondary" style={{ fontSize: '12px' }}>
                  R{record.rowNumber}-G{record.gridNumber}
                </Text>
              )}
            </Space>
          );
        }
        return <Tag color="default">Manual Location</Tag>;
      },
    },
    {
      title: 'Zone',
      dataIndex: 'zone',
      key: 'zone',
      width: '8%',
      render: (text: string) => <Tag color="blue">{text}</Tag>,
    },
    {
      title: 'Position',
      key: 'position',
      width: '10%',
      render: (_: any, record: Location) => (
        <Text type="secondary">
          Row {record.row}, Grid {record.grid}
        </Text>
      ),
    },
    {
      title: 'Coordinates',
      key: 'coordinates',
      width: '12%',
      render: (_: any, record: Location) => (
        <Text type="secondary" style={{ fontSize: '12px' }}>
          ({record.xCoordinates}, {record.yCoordinates}, {record.zCoordinates})
        </Text>
      ),
    },
    {
      title: 'Capacity',
      dataIndex: 'capacity',
      key: 'capacity',
      width: '10%',
      render: (capacity: number) => <Tag color="green">{capacity} units</Tag>,
    },
    {
      title: 'Description',
      dataIndex: 'description',
      key: 'description',
      width: '13%',
      render: (text: string) => (
        <Text type="secondary" ellipsis={{ tooltip: text }}>
          {text || 'No description'}
        </Text>
      ),
    },
    {
      title: 'Created',
      dataIndex: 'createdDate',
      key: 'createdDate',
      width: '10%',
      render: (date: string) => <Text type="secondary">{formatDate(date)}</Text>,
    },
    
  ];

  return (
    <div style={{ minHeight: '100vh', background: '#f0f2f5', padding: '24px' }}>
            <style>{`
              .ant-pagination .ant-pagination-item-active {
                border-color: ${AppColors.primary} !important;
              }
              .ant-pagination .ant-pagination-item-active a {
                color: ${AppColors.primary} !important;
              }
              .custom-button-primary:hover {
                background-color: ${AppColors.primary} !important;
                border-color: ${AppColors.primary} !important;
              }
              .custom-button-default:hover {
                color: ${AppColors.primary} !important;
                border-color: ${AppColors.primary} !important;
              }
              
              .custom-button-default .ant-select-selector:hover {
                border-color: ${AppColors.primary} !important;
              }
              .custom-button-default.ant-select-focused .ant-select-selector {
                border-color: ${AppColors.primary} !important;
                box-shadow: 0 0 0 2px ${AppColors.primary}20 !important;
              }
              
              .ant-select-dropdown .ant-select-item-option-active:not(.ant-select-item-option-disabled) {
                background-color: ${AppColors.primary}10 !important;
              }
              .ant-select-dropdown .ant-select-item-option-selected:not(.ant-select-item-option-disabled) {
                background-color: ${AppColors.primary}20 !important;
                color: ${AppColors.primary} !important;
              }
            `}</style>
      <div style={{ maxWidth: '1600px', margin: '0 auto' }}>
        <Space direction="vertical" size="large" style={{ width: '100%' }}>
          <Card>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <Title level={2}>Locations</Title>
                <Text type="secondary">
                  Manage warehouse locations and storage zones
                  {isAdmin && <Tag color="red" style={{ marginLeft: '8px' }}>Admin</Tag>}
                </Text>
              </div>
            </div>
          </Card>

          <Row gutter={16}>
            <Col span={6}>
              <Card>
                <Statistic
                  title="Total Locations"
                  value={stats.total}
                  prefix={<EnvironmentOutlined />}
                  valueStyle={{ color: '#1890ff' }}
                />
              </Card>
            </Col>
            <Col span={6}>
              <Card>
                <Statistic
                  title="Auto-Generated (From Racks)"
                  value={stats.autoGenerated}
                  prefix={<AppstoreOutlined />}
                  valueStyle={{ color: '#52c41a' }}
                />
              </Card>
            </Col>
            <Col span={6}>
              <Card>
                <Statistic
                  title="With Rack"
                  value={stats.withRack}
                  valueStyle={{ color: '#722ed1' }}
                />
              </Card>
            </Col>
            <Col span={6}>
              <Card>
                <Statistic
                  title="Manual Locations"
                  value={stats.withoutRack}
                  valueStyle={{ color: '#fa8c16' }}
                />
              </Card>
            </Col>
          </Row>

          <Card title="Filters">
            <Space size="large" style={{ width: '100%' }}>
              <Space direction="vertical" style={{ flex: 1 }}>
                <Text strong>Blueprint</Text>
                <Select
                  className="custom-button-default"
                  style={{ width: 300 }}
                  placeholder="Filter by blueprint"
                  allowClear
                  value={selectedBlueprint}
                  onChange={(value) => {
                    setSelectedBlueprint(value);
                    setSelectedRack(null);
                  }}
                  options={blueprints?.map((bp) => ({
                    label: bp.name,
                    value: bp.id,
                  }))}
                />
              </Space>

              <Space direction="vertical" style={{ flex: 1 }}>
                <Text strong>Rack</Text>
                <Select
                className="custom-button-default"
                  style={{ width: 300 }}
                  placeholder="Filter by rack"
                  allowClear
                  value={selectedRack}
                  onChange={setSelectedRack}
                  disabled={!selectedBlueprint}
                  options={racks?.map((rack) => ({
                    label: rack.name,
                    value: rack.id,
                  }))}
                />
              </Space>

              <Button
                icon={<ClearOutlined />}
                onClick={handleClearFilters}
                style={{ marginTop: '24px' }}
                className="custom-button-default"
              >
                Clear Filters
              </Button>
            </Space>
          </Card>

          <Card>
            <Table
              columns={columns}
              dataSource={filteredLocations}
              rowKey="id"
              loading={isLoading}
              pagination={{ pageSize: 10 }}
            />
          </Card>
        </Space>

      </div>
    </div>
  );
}